//! The **expression vocabulary** — the ~180 tokens the M2 expression recognizer ranks over.
//!
//! ## Why the expression path must NOT rank over all 1,188 classes
//!
//! DESIGN §4.3 specifies the expression recognizer at "~120 classes (CROHME's 111 +
//! extras)". When M2 was built it quietly reused the full symbol-*lookup* vocabulary —
//! and that is how a hand-drawn `x` came back `\upchi`, a `+` came back `\dashv`, and a
//! `1` came back `\Lbag`: the everyday token had to out-score five exotic look-alikes it
//! can never beat with 59 training samples. Every HMER system restricts the expression
//! vocabulary, because **the vocabulary is the domain prior**. `\Lbag` is not a plausible
//! reading of anything in `2x + 3 = 7`.
//!
//! The M1 lookup path (`--recognize`) is deliberately untouched: there, ranking over all
//! 1,188 classes is the product — you drew an exotic glyph precisely because you want its
//! name.
//!
//! Every entry is verified against the shipped label space by a test in `ink2tex-desktop`
//! (`vocabulary_entries_exist_in_the_label_space`) — an entry the classifier cannot emit
//! is dead weight that silently narrows the mask.

/// Tokens plausible inside an everyday mathematical expression, in the exact form the
/// classifier emits them: literals (`x`, `7`, `+`) for the HWRT-contributed tokens, and
/// Detexify symbolIds (`latex:latex2e:alpha`) for the rest.
pub const EXPRESSION_TOKENS: &[&str] = &[
    // Device-collected tokens (train/collected/): absent from every public dataset.
    "=",
    "(",
    ")",
    "t",
    "latex:amssymb:geq",
    "latex:amssymb:gg",
    "latex:amssymb:leq",
    "latex:amssymb:ll",
    "latex:amssymb:neq",
    "latex:amssymb:varnothing",
    "latex:dsfont:mathds-lbrace-C-rbrace",
    "latex:dsfont:mathds-lbrace-N-rbrace",
    "latex:dsfont:mathds-lbrace-Q-rbrace",
    "latex:dsfont:mathds-lbrace-R-rbrace",
    "latex:dsfont:mathds-lbrace-Z-rbrace",
    "latex:latex2e:Delta",
    "latex:latex2e:Gamma",
    "latex:latex2e:Im",
    "latex:latex2e:Lambda",
    "latex:latex2e:Leftarrow",
    "latex:latex2e:Leftrightarrow",
    "latex:latex2e:Omega",
    "latex:latex2e:Phi",
    "latex:latex2e:Pi",
    "latex:latex2e:Psi",
    "latex:latex2e:Re",
    "latex:latex2e:Rightarrow",
    "latex:latex2e:Sigma",
    "latex:latex2e:Theta",
    "latex:latex2e:Upsilon",
    "latex:latex2e:Xi",
    "latex:latex2e:aleph",
    "latex:latex2e:alpha",
    "latex:latex2e:angle",
    "latex:latex2e:approx",
    "latex:latex2e:ast",
    "latex:latex2e:beta",
    "latex:latex2e:bullet",
    "latex:latex2e:cap",
    "latex:latex2e:cdot",
    "latex:latex2e:cdots",
    "latex:latex2e:chi",
    "latex:latex2e:circ",
    "latex:latex2e:cong",
    "latex:latex2e:cup",
    "latex:latex2e:delta",
    "latex:latex2e:div",
    "latex:latex2e:downarrow",
    "latex:latex2e:ell",
    "latex:latex2e:emptyset",
    "latex:latex2e:epsilon",
    "latex:latex2e:equiv",
    "latex:latex2e:eta",
    "latex:latex2e:exists",
    "latex:latex2e:forall",
    "latex:latex2e:gamma",
    "latex:latex2e:hbar",
    "latex:latex2e:in",
    "latex:latex2e:infty",
    "latex:latex2e:int",
    "latex:latex2e:iota",
    "latex:latex2e:kappa",
    "latex:latex2e:lambda",
    "latex:latex2e:langle",
    "latex:latex2e:lceil",
    "latex:latex2e:ldots",
    "latex:latex2e:leftarrow",
    "latex:latex2e:leftrightarrow",
    "latex:latex2e:lfloor",
    "latex:latex2e:longrightarrow",
    "latex:latex2e:mapsto",
    "latex:latex2e:mid",
    "latex:latex2e:mp",
    "latex:latex2e:mu",
    "latex:latex2e:nabla",
    "latex:latex2e:neg",
    "latex:latex2e:ni",
    "latex:latex2e:nu",
    "latex:latex2e:oint",
    "latex:latex2e:omega",
    "latex:latex2e:ominus",
    "latex:latex2e:oplus",
    "latex:latex2e:otimes",
    "latex:latex2e:parallel",
    "latex:latex2e:partial",
    "latex:latex2e:perp",
    "latex:latex2e:phi",
    "latex:latex2e:pi",
    "latex:latex2e:pm",
    "latex:latex2e:prime",
    "latex:latex2e:prod",
    "latex:latex2e:propto",
    "latex:latex2e:psi",
    "latex:latex2e:rangle",
    "latex:latex2e:rceil",
    "latex:latex2e:rfloor",
    "latex:latex2e:rho",
    "latex:latex2e:rightarrow",
    "latex:latex2e:setminus",
    "latex:latex2e:sigma",
    "latex:latex2e:sim",
    "latex:latex2e:simeq",
    "latex:latex2e:sqrt-lbrace-rbrace",
    "latex:latex2e:subset",
    "latex:latex2e:subseteq",
    "latex:latex2e:sum",
    "latex:latex2e:supset",
    "latex:latex2e:supseteq",
    "latex:latex2e:surd",
    "latex:latex2e:tau",
    "latex:latex2e:theta",
    "latex:latex2e:times",
    "latex:latex2e:uparrow",
    "latex:latex2e:upsilon",
    "latex:latex2e:varepsilon",
    "latex:latex2e:varphi",
    "latex:latex2e:varsigma",
    "latex:latex2e:vartheta",
    "latex:latex2e:vee",
    "latex:latex2e:wedge",
    "latex:latex2e:xi",
    "latex:latex2e:zeta",
    "latex:textcomp:textsurd",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "+",
    "-",
    "<",
    ">",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
];

/// Is this label rankable in expression context?
pub fn in_expression_vocab(label: &str) -> bool {
    EXPRESSION_TOKENS.contains(&label)
}
